mod config;
mod pacman;
mod printer;
mod shell;

use crate::config::{SysConfig, read_file, save_old_config};
use crate::pacman::install_if_missing;
use crate::printer::{print_error, print_header, print_warning};
use crate::shell::{check_for_shell_warnings, run};
use std::fs;

fn main() {
    print_header("Processing system configuration");

    let cfg = SysConfig::read_or_generate_config("/etc/sysconfig");
    let prev = config::parse_config(config::read_file("/etc/sysconfig.old"));

    if !cfg.validate_config() {
        print_error("Config validation failed. Aborting.", None);
        std::process::exit(-1);
    }

    if !prev.validate_config() {
        print_error("Old config validation failed. Aborting.", None);
        std::process::exit(-1);
    }

    let (add, remove) = cfg.difference(&prev);

    print_header("Upgrading system");
    run("/usr/bin/pacman", &["-Syu", "--color", "never"]);
    if cfg
        .packages
        .as_ref()
        .is_some_and(|p| p.contains(&"flatpak".to_string()))
    {
        run("/usr/bin/flatpak", &["update"]);
    }
    if cfg
        .packages
        .as_ref()
        .is_some_and(|p| p.contains(&"yay".to_string()))
    {
        run("/usr/bin/yay", &[]);
    }
    if cfg
        .packages
        .as_ref()
        .is_some_and(|p| p.contains(&"paru".to_string()))
    {
        print_warning(
            "We strongly recommend you to use yay instead of paru.",
            None,
        );
        run("/usr/bin/paru", &[]);
    }

    print_header("Processing package changes");
    if !add.is_empty() && !install_if_missing(&add) {
        print_error(
            "Failed to install packages. Fix configuration to remove the error.",
            None,
        );
    }
    if !remove.is_empty() && !run("/usr/bin/pacman", &["-Rns", "--color", "never"]) {
        print_error(
            "Failed to remove packages. Fix configuration to remove the error.",
            None,
        );
    }
    if add.is_empty() && remove.is_empty() {
        println!("packages unchanged");
    }

    print_header("Rebuilding system configuration");

    let shells_data = cfg
        .shells
        .as_ref()
        .map(|s| s.join("\n"))
        .unwrap_or(String::from(
            r#"
/bin/sh
/bin/bash
/bin/rbash
/usr/bin/sh
/usr/bin/bash
/usr/bin/rbash
/usr/bin/systemd-home-fallback-shell
/usr/bin/git-shell"#,
        ));

    fs::write("/etc/shells", format!(
        "# file autogenerated\n# please edit the system configuration at /etc/sysconfig instead\n\n# Pathnames of valid login shells.\n# See shells(5) for details.\n\n{}",
        shells_data
    )).unwrap_or_else(|e| print_error("Failed to write /etc/shells", Some(&e.to_string())));

    check_for_shell_warnings();

    print_header("Backing up config");
    save_old_config(&read_file("/etc/sysconfig").unwrap_or_default());
    println!("config backed up to /etc/sysconfig.old");
}
